In [1]:
print("Hello World")

Hello World


In [2]:
1+1

2

In [3]:
import numpy as np

In [4]:
ones = np.ones(10)

In [5]:
ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
ones+ones

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.])

In [7]:
ones*3

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [8]:
ones+2

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [9]:
rands = np.random.rand(10)

In [10]:
rands

array([ 0.21537655,  0.25804495,  0.86041818,  0.93884997,  0.59319745,
        0.97919382,  0.15241844,  0.93297899,  0.81740595,  0.51652753])

In [11]:
rands[0]

0.21537654521629146

In [12]:
rands[:3]

array([ 0.21537655,  0.25804495,  0.86041818])

In [13]:
rands[-3:]

array([ 0.93297899,  0.81740595,  0.51652753])

In [15]:
rands[np.where(rands < 0.5)]

array([ 0.21537655,  0.25804495,  0.15241844])

In [16]:
rands+ones

array([ 1.21537655,  1.25804495,  1.86041818,  1.93884997,  1.59319745,
        1.97919382,  1.15241844,  1.93297899,  1.81740595,  1.51652753])

In [17]:
np.concatenate((ones,ones))

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
np.array([1,2,3])

array([1, 2, 3])

In [24]:
np.array([ones,rands])[:,3:]

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ],
       [ 0.93884997,  0.59319745,  0.97919382,  0.15241844,  0.93297899,
         0.81740595,  0.51652753]])

In [26]:
my_list = range(int(1e4))
my_array = np.arange(int(1e4))

In [28]:
%%timeit
[i*2 for i in my_list]

1000 loops, best of 3: 758 µs per loop


In [29]:
%%timeit
my_array*2

The slowest run took 10.64 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 14.7 µs per loop
